name: CodeCov

on:
  push:
    branches-ignore:
      - version/*

  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test and push to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
